### ISSUE TITLE
2 problems about GraphARM

### ISSUE THREAD

**Issue by Jary-lrj** [caio-freitas/GraphDiffusionImitate#61]
Thank you for your paper and work. But I found 2 problems:
1. GraphARM does not seem to converge. I used the ZINC data set you provided. The batch_size is 1 and the epoch is 1e4. The final Loss does not converge to a certain value. Is this normal?
2. When I use my own data set to train GraphARM, there will even be an error that the first few epochs can be trained normally, but then the tensor dimension of edge_index and the dimension of x cannot match. I checked your data processing logic and edge_index.shape[1] must be the square of shape[0] of x. But I will get an error such as when x.shape[0] is 26, edge_index.shape[1]=484 instead of 676. I've checked that my data is correct, does this mean there's something wrong with your code?
Looking forward to your reply, thank you again!

**Comment by caio-freitas** [comment]
GraphARM was moved to another repo
